[pyprland]
plugins = [
 "expose",
 "fetch_client_menu",
 "lost_windows",
 "magnify",
 "layout_center",
 "scratchpads",
 "shift_monitors",
 "toggle_special",
 "workspaces_follow_focus",
]

[magnify]
factor = 2
duration = 10
